In [1]:
import pandas as pd

df = pd.read_csv(
    "C:/Data Analyst Projects/01_Retail_Sales_Profitability_Analytics/SuperStore_Sales_Dataset.csv",
    encoding="latin1"
)

In [2]:
df.head()

,ï»¿Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,ImationÂ Clip USBÂ flash driveÂ - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [3]:
df.shape

(5901, 23)

In [4]:
df.columns.tolist()

['ï»¿Row ID+O6G3A1:R6',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Profit',
 'Returns',
 'Payment Mode',
 'ind1',
 'ind2']

In [6]:
df.dtypes

ï»¿Row ID+O6G3A1:R6      int64
Order ID                   str
Order Date                 str
Ship Date                  str
Ship Mode                  str
Customer ID                str
Customer Name              str
Segment                    str
Country                    str
City                       str
State                      str
Region                     str
Product ID                 str
Category                   str
Sub-Category               str
Product Name               str
Sales                  float64
Quantity                 int64
Profit                 float64
Returns                float64
Payment Mode               str
ind1                   float64
ind2                   float64
dtype: object

In [7]:
df.isnull().sum()

ï»¿Row ID+O6G3A1:R6       0
Order ID                  0
Order Date                0
Ship Date                 0
Ship Mode                 0
Customer ID               0
Customer Name             0
Segment                   0
Country                   0
City                      0
State                     0
Region                    0
Product ID                0
Category                  0
Sub-Category              0
Product Name              0
Sales                     0
Quantity                  0
Profit                    0
Returns                5614
Payment Mode              0
ind1                   5901
ind2                   5901
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.iloc[:, 0].duplicated().sum()

np.int64(1)

In [10]:
print("Unique Orders:", df["Order ID"].nunique())
print("Unique Customers:", df["Customer ID"].nunique())
print("Unique Products:", df["Product ID"].nunique())

Unique Orders: 3003
Unique Customers: 773
Unique Products: 1755

In [11]:
df["Category"].value_counts()

Category
Office Supplies    3569
Furniture          1249
Technology         1083
Name: count, dtype: int64

In [12]:
df["Sub-Category"].value_counts()

Sub-Category
Binders        915
Paper          825
Furnishings    573
Phones         519
Storage        498
Art            465
Accessories    461
Chairs         355
Appliances     279
Labels         211
Tables         190
Envelopes      133
Bookcases      131
Fasteners      124
Supplies       119
Machines        65
Copiers         38
Name: count, dtype: int64

In [13]:
print(df["Order Date"].head(10))
print(df["Ship Date"].head(10))

0    01-01-2019
1    02-01-2019
2    02-01-2019
3    03-01-2019
4    03-01-2019
5    03-01-2019
6    03-01-2019
7    03-01-2019
8    03-01-2019
9    04-01-2019
Name: Order Date, dtype: str
0    07-01-2019
1    07-01-2019
2    07-01-2019
3    05-01-2019
4    08-01-2019
5    08-01-2019
6    08-01-2019
7    08-01-2019
8    08-01-2019
9    09-01-2019
Name: Ship Date, dtype: str

In [14]:
order_date_parts = df["Order Date"].str.split("-")

print(
    "First Part Max:",
    order_date_parts.str[0].astype(int).max()
)

print(
    "Second part max:",
    order_date_parts.str[1].astype(int).max()
)

First Part Max: 31
Second part max: 12

In [15]:
df["Order Date Clean"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y"
)

df["Ship Date Clean"] = pd.to_datetime(
    df["Ship Date"],
    format="%d-%m-%Y"
)

In [16]:
df[["Order Date", "Order Date Clean", "Ship Date", "Ship Date Clean"]].head(10)

   Order Date Order Date Clean   Ship Date Ship Date Clean
0  01-01-2019       2019-01-01  07-01-2019      2019-01-07
1  02-01-2019       2019-01-02  07-01-2019      2019-01-07
2  02-01-2019       2019-01-02  07-01-2019      2019-01-07
3  03-01-2019       2019-01-03  05-01-2019      2019-01-05
4  03-01-2019       2019-01-03  08-01-2019      2019-01-08
5  03-01-2019       2019-01-03  08-01-2019      2019-01-08
6  03-01-2019       2019-01-03  08-01-2019      2019-01-08
7  03-01-2019       2019-01-03  08-01-2019      2019-01-08
8  03-01-2019       2019-01-03  08-01-2019      2019-01-08
9  04-01-2019       2019-01-04  09-01-2019      2019-01-09

In [17]:
print(
    "Invalid Order Dates:", df["Order Date Clean"].isna().sum()
)

print(
    "Invalid Ship Dates:", df["Ship Date Clean"].isna().sum()
)

Invalid Order Dates: 0
Invalid Ship Dates: 0

In [18]:
(df["Ship Date Clean"] < df["Order Date Clean"]).sum()

np.int64(0)

In [19]:
df["Returns"].value_counts(dropna=False)

Returns
NaN    5614
1.0     287
Name: count, dtype: int64

In [20]:
print("Returned rows:", (df["Returns"] == 1).sum())
print("Non-returned/blank rows:", df["Returns"].isna().sum())

Returned rows: 287
Non-returned/blank rows: 5614

In [21]:
df["ind1"].value_counts(dropna=False)

ind1
NaN    5901
Name: count, dtype: int64

In [22]:
df["ind2"].value_counts(dropna=False)

ind2
NaN    5901
Name: count, dtype: int64

In [23]:
print("Sales Min:", df["Sales"].min())
print("Sales Max:", df["Sales"].max())

print("Quantity Min:", df["Quantity"].min())
print("Quantity Max:", df["Quantity"].max())

print("Profit Min:", df["Profit"].min())
print("Profit Max:", df["Profit"].max())

Sales Min: 0.836
Sales Max: 9099.93
Quantity Min: 1
Quantity Max: 14
Profit Min: -6599.978
Profit Max: 8399.976

In [24]:
print("Negative Sales:", (df["Sales"] < 0).sum())
print("Zero/Negative Quantity:", (df["Quantity"] <= 0).sum())

Negative Sales: 0
Zero/Negative Quantity: 0

In [25]:
text_columns = df.select_dtypes(include="str").columns

for col in text_columns:
    blank_count = df[col].str.strip().eq("").sum()
    if blank_count > 0:
        print(f"{col}: {blank_count} blank values")

In [26]:
df = df.rename(columns={
    "ï»¿Row ID+O6G3A1:R6": "Row ID"
})

In [27]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Profit',
 'Returns',
 'Payment Mode',
 'ind1',
 'ind2',
 'Order Date Clean',
 'Ship Date Clean']

In [28]:
df[["Order Date", "Order Date Clean", "Ship Date", "Ship Date Clean"]].head()

   Order Date Order Date Clean   Ship Date Ship Date Clean
0  01-01-2019       2019-01-01  07-01-2019      2019-01-07
1  02-01-2019       2019-01-02  07-01-2019      2019-01-07
2  02-01-2019       2019-01-02  07-01-2019      2019-01-07
3  03-01-2019       2019-01-03  05-01-2019      2019-01-05
4  03-01-2019       2019-01-03  08-01-2019      2019-01-08

In [29]:
df["Order Date"] = df["Order Date Clean"]
df["Ship Date"] = df["Ship Date Clean"]

In [30]:
df = df.drop(
    columns = ["Order Date Clean", "Ship Date Clean"]
)

In [31]:
df.shape

(5901, 23)

In [32]:
df.dtypes[["Order Date", "Ship Date"]]

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [33]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Profit',
 'Returns',
 'Payment Mode',
 'ind1',
 'ind2']

In [34]:
df = df.drop(columns=["ind1", "ind2"])

In [35]:
df.shape

(5901, 21)

In [36]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Profit',
 'Returns',
 'Payment Mode']

In [37]:
df.loc[df["Returns"].notna(),"Returns"].unique()

array([1.])

In [38]:
df["Returns"] = df["Returns"].fillna(0).astype(int)

In [39]:
df["Returns"].value_counts()

Returns
0    5614
1     287
Name: count, dtype: int64

In [40]:
text_columns = df.select_dtypes(include="str").columns

for col in text_columns:
    leading_trailing_spaces = (
        df[col].astype(str).str.strip().ne(df[col].astype(str))
    ).sum()

    if leading_trailing_spaces > 0:
        print(f"{col}: {leading_trailing_spaces} values with extra spaces")

In [41]:
print("Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Row IDs:", df["Row ID"].duplicated().sum())

Shape: (5901, 21)
Missing Values: 0
Duplicate Rows: 0
Duplicate Row IDs: 1

In [42]:
df.loc[df["Row ID"].duplicated(keep=False)].sort_values("Row ID")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode
0,4918,CA-2019-160304,2019-01-01,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.940,1,28.2668,0,Online
4773,4918,CA-2020-163125,2020-10-09,2020-10-11,Second Class,MB-17305,Maria Bertelson,Consumer,United States,League City,...,Central,FUR-CH-10001802,Furniture,Chairs,Hon Every-Day Chair Series Swivel Task Chairs,272.058,3,-32.6646,0,COD

In [43]:
print("Invalid Order/Ship Dates:", (df["Ship Date"] < df["Order Date"]).sum())
print("Negative Sales:", (df["Sales"] < 0).sum())
print("Zero/Negative Quantity:", (df["Quantity"] <= 0).sum())

Invalid Order/Ship Dates: 0
Negative Sales: 0
Zero/Negative Quantity: 0

In [44]:
df.to_csv(
    "C:/Data Analyst Projects/01_Retail_Sales_Profitability_Analytics/SuperStore_Sales_Dataset_Cleaned.csv",
    index=False
)

In [45]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()
total_quantity = df["Quantity"].sum()

profit_margin = (total_profit / total_sales) * 100
average_order_value = total_sales / total_orders
return_rate = (df["Returns"].sum() / len(df)) * 100

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Profit Margin %:", profit_margin)
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Total Quantity:", total_quantity)
print("Average Order Value:", average_order_value)
print("Return Rate %:", return_rate)

Total Sales: 1565804.3232
Total Profit: 175262.1059
Profit Margin %: 11.193103972392967
Total Orders: 3003
Total Customers: 773
Total Quantity: 22317
Average Order Value: 521.413361038961
Return Rate %: 4.863582443653618

In [46]:
yearly_performance = (
    df
    .groupby(df["Order Date"].dt.year, as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
    .rename(columns={"Order Date": "Order Year"})
)

yearly_performance["Profit Margin %"] = (
    yearly_performance["Profit"] /
    yearly_performance["Sales"] * 100
)

print(yearly_performance.to_string(index=False))

 Order Year        Sales     Profit  Orders  Quantity  Profit Margin %
       2019  564679.5380 81823.4411    1315      9838        14.490244
       2020 1001124.7852 93438.6648    1688     12479         9.333368

In [47]:
category_performance = (
    df
    .groupby("Category", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

category_performance["Profit Margin %"] = (
    category_performance["Profit"] /
    category_performance["Sales"] * 100
)

print(category_performance.to_string(index=False))

       Category       Sales     Profit  Orders  Quantity  Profit Margin %
      Furniture 451508.6452 10006.6112    1040      4631         2.216261
Office Supplies 643707.6870 74797.2461    2219     13625        11.619753
     Technology 470587.9910 90458.2486     915      4061        19.222388

In [48]:
subcategory_performance = (
    df
    .groupby("Sub-Category", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

subcategory_performance["Profit Margin %"] = (
    subcategory_performance["Profit"] /
    subcategory_performance["Sales"] * 100
)

print(subcategory_performance.sort_values(
    "Profit Margin %",
    ascending=True
).to_string(index=False))

Sub-Category       Sales      Profit  Orders  Quantity  Profit Margin %
      Tables 119293.7430 -11091.6365     186       736        -9.297752
    Supplies  36720.9860  -1654.2767     117       408        -4.504990
   Bookcases  57577.6862   -342.8883     130       474        -0.595523
    Machines  91987.5610     38.1024      64       250         0.041421
   Fasteners  15205.2380    598.4175     124       540         3.935601
         Art  50762.9760   3635.9257     422      1779         7.162554
      Chairs 181945.9980  13406.7032     331      1288         7.368507
 Furnishings  92691.2180   8034.4328     527      2133         8.667955
     Storage 150341.3180  13607.0875     459      1830         9.050797
     Binders 174978.3900  17885.3759     785      3670        10.221477
      Phones 196563.5460  22308.9179     487      1908        11.349469
      Labels  19397.4560   2937.2212     200       811        15.142301
  Appliances  80305.2470  13166.6098     271      1050        16.395703
 Accessories 122301.0860  25336.6455     422      1761        20.716615
   Envelopes  16542.4640   3508.5073     133       463        21.209097
       Paper  99453.6120  21112.3779     719      3074        21.228367
     Copiers  59735.7980  42774.5828      38       142        71.606280

In [49]:
product_performance = (
    df
    .groupby(["Product ID", "Product Name"], as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

product_performance["Profit Margin %"] = (
    product_performance["Profit"] /
    product_performance["Sales"] * 100
)

print(
    product_performance
    .sort_values("Profit")
    .head(10)
    .to_string(index=False)
)

     Product ID                                                         Product Name     Sales     Profit  Orders  Quantity  Profit Margin %
TEC-MA-10000418                            Cubify CubeX 3D Printer Double Head Print  9323.969 -6239.9792       2         7       -66.924066
TEC-MA-10004125                            Cubify CubeX 3D Printer Triple Head Print  3009.980 -3839.9904       1         4      -127.575280
TEC-MA-10000822                            Lexmark MX611dhe Monochrome Laser Printer  5676.967 -2719.9840       2         7       -47.912627
FUR-TA-10001889                 Bush Advantage Collection Racetrack Conference Table  4334.100 -2019.2396       4        18       -46.589594
OFF-BI-10001120                                 Ibico EPK-21 Electric Binding System  6437.966 -1285.1932       2         8       -19.962721
OFF-SU-10002881                   Martin Yale Chadless Opener Electric Letter Opener 12268.902 -1232.5588       4        16       -10.046203
FUR-TA-10004289    BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables  1052.500  -986.5625       2        13       -93.735154
FUR-TA-10004256 Bretford âJust In Timeâ Height-Adjustable Multi-Task Work Tables  3869.900  -964.1940       4        17       -24.915217
TEC-MA-10001695                 Zebra GK420t Direct Thermal/Thermal Transfer Printer   703.710  -938.2800       1         6      -133.333333
TEC-MA-10002210          Epson TM-T88V Direct Thermal Printer - Monochrome - Desktop   692.995  -935.9595       1         7      -135.060065

In [50]:
print(
    product_performance
    .sort_values("Profit", ascending=False)
    .head(10)
    .to_string(index=False)
)

     Product ID                                                       Product Name     Sales     Profit  Orders  Quantity  Profit Margin %
TEC-CO-10004722                              Canon imageCLASS 2200 Advanced Copier 14076.824 25199.9280       5        20       179.017142
TEC-CO-10001449                               Hewlett Packard LaserJet 3310 Copier 13837.732  6407.8932       6        31        46.307395
TEC-MA-10001047                   3D Systems Cube Printer, 2nd Generation, Magenta 14334.890  3717.9714       2        11        25.936519
TEC-MA-10001127          HP Designjet T520 Inkjet Large Format Printer - 24" Color  4749.950  2799.9840       1         5        58.947652
OFF-BI-10001359                         GBC DocuBind TL300 Electric Binding System 12890.258  2753.7593       6        21        21.363105
TEC-MA-10003979                                  Ativa V4110MDD Micro-Cut Shredder  4899.930  2400.9657       1         7        49.000000
OFF-AP-10002945 Honeywell Enviracaire Portable HEPA Air Cleaner for 17' x 22' Room  7275.810  2396.1805       5        29        32.933522
TEC-AC-10003033 Plantronics CS510 - Over-the-Head monaural Wireless Headset System  7664.850  2062.1875       7        25        26.904473
TEC-CO-10003763                                 Canon PC1060 Personal Laser Copier  5599.920  1889.9730       2        10        33.750000
TEC-AC-10003870                LogitechÂ Z-906 Speaker sys - home theater - 5.1-CH  4657.860  1847.9440       3        14        39.673670

In [51]:
customer_performance = (
    df
    .groupby(["Customer ID", "Customer Name"], as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

customer_performance["Profit Margin %"] = (
    customer_performance["Profit"] /
    customer_performance["Sales"] * 100
)

print("Top 10 Customers by Sales")
print(
    customer_performance
    .sort_values("Sales", ascending=False)
    .head(10)
    .to_string(index=False)
)

print("\nTop 10 Customers by Profit")
print(
    customer_performance
    .sort_values("Profit", ascending=False)
    .head(10)
    .to_string(index=False)
)

Top 10 Customers by Sales
Customer ID   Customer Name     Sales    Profit  Orders  Quantity  Profit Margin %
   CJ-12010 Caroline Jumper 11596.974  858.7414       8        83         7.404875
   KF-16285  Karen Ferguson 10941.274 1577.6134       6        61        14.418919
   SV-20365     Seth Vernon 10751.148 1610.0020       7        88        14.975164
   HW-14935 Helen Wasserman 10074.934 2146.9635       7        76        21.309951
   EH-13765    Edward Hooks  9542.988 1164.6312       9        89        12.204052
   BS-11365    Bill Shonely  9199.780 2405.3645       2        18        26.145892
   PK-19075       Pete Kriz  8812.054 2024.9500      11       101        22.979319
   JL-15835        John Lee  8765.332  839.9550       7        94         9.582695
   AB-10060 Adam Bellavance  8167.080 2045.8747       7        54        25.050259
   JW-15220       Jane Waco  7933.554 2084.5100       5        44        26.274605

Top 10 Customers by Profit
Customer ID Customer Name    Sales    Profit  Orders  Quantity  Profit Margin %
   TC-20980  Tamara Chand 1344.052 8764.9483       2        20       652.128660
   RB-19360  Raymond Buch 5041.339 6976.0959       6        71       138.377838
   HL-15040  Hunter Lopez 6091.108 5174.3968       4        16        84.950009
   AB-10105 Adrian Barton 6276.909 5088.9448       8        44        81.074057
   TA-21385  Tom Ashbrook 3715.770 4523.3625       3        24       121.734190
   AR-10540   Andy Reiter 6353.820 2617.2154       3        22        41.191211
   DR-12940 Daniel Raglin 6408.616 2549.7344       4        33        39.786038
   SE-20110  Sanjit Engle 7821.978 2436.9525       7        54        31.155195
   BS-11365  Bill Shonely 9199.780 2405.3645       2        18        26.145892
   KD-16270 Karen Daniels 6317.162 2318.7099       3        24        36.704930

In [52]:
region_performance = (
    df
    .groupby("Region", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

region_performance["Profit Margin %"] = (
    region_performance["Profit"] /
    region_performance["Sales"] * 100
)

print(region_performance.to_string(index=False))

 Region       Sales     Profit  Orders  Quantity  Profit Margin %
Central 341007.5242 27450.0071     711      5239         8.049678
   East 450234.6660 53400.4243     844      6251        11.860576
  South 252121.0810 26551.7163     487      3529        10.531335
   West 522441.0520 67859.9582     961      7298        12.989017

In [54]:
return_by_category = (
    df
    .groupby("Category", as_index=False)
    .agg(
        Total_Rows=("Returns", "size"),
        Returned_Rows=("Returns", "sum")
    )
)

return_by_category["Return Rate %"] = (
    return_by_category["Returned_Rows"] /
    return_by_category["Total_Rows"] * 100
)

print(return_by_category.to_string(index=False))

       Category  Total_Rows  Returned_Rows  Return Rate %
      Furniture        1249             70       5.604484
Office Supplies        3569            165       4.623144
     Technology        1083             52       4.801477

In [55]:
payment_performance = (
    df
    .groupby("Payment Mode", as_index=False)
    .agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order ID", "nunique"),
        Quantity=("Quantity", "sum")
    )
)

payment_performance["Profit Margin %"] = (
    payment_performance["Profit"] /
    payment_performance["Sales"] * 100
)

print(payment_performance.to_string(index=False))

Payment Mode       Sales     Profit  Orders  Quantity  Profit Margin %
         COD 667417.7513 82092.4250    1717      9247        12.300006
       Cards 344393.1112 39122.1575     985      4903        11.359739
      Online 553993.4607 54047.5234    1562      8167         9.755986